### ISSUE TITLE
Implement Edamam API

### ISSUE THREAD

**Issue by WhiT3Kr0w** [eat-well/eatwell-web#14]
We now have access to Edamam Food Database which we need to implement instead of using the temporary API endpoints that are pointing to the MariaDB foods table.

- [x] Setup API endpoint
- [x] Fetch foods by name/keyword
- [ ] Show foods in autocomplete fields

Edamam API docs:
https://developer.edamam.com/food-database-api-docs

**Comment by mulholio** [comment]
Presumably, this is running off of the Now branch?  You will get some icky conflicts if it's not.

Separately, how is this data related to other proprietary data (e.g. Recommendations)?

**Comment by WhiT3Kr0w** [comment]
> Presumably, this is running off of the Now branch? You will get some icky conflicts if it's not.
> 
> Separately, how is this data related to other proprietary data (e.g. Recommendations)?

I've fixed conflicts.
This data is just for the Edamam API. To fetch food data and populate fields in the app.
For the recommendations we will need to setup another DB to replace MariaDB. Once the nutritionists fill in the recommendation fields using the food data from the Edamam API, we will then save those into the database.
