### ISSUE TITLE
Implement login functionality on UI

### ISSUE THREAD

**Issue by mulholio** [eat-well/eatwell-web#6]
Nutritionists should access EatWell through a login portal to ensure we restrict access and so that who added what data can be tracked.

Possible implementations:
- Roll our own using Cookies and JWT
- [Passport JS](http://www.passportjs.org/docs/)
- Firebase Auth
- [Auth0](https://auth0.com/)
- https://aws.amazon.com/cognito/

**Comment by WhiT3Kr0w** [comment]
Auth0 implemented
